[package]
name = "ytmtui-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1"
ytm-api = { path = "../crates/ytm-api" }
ytm-config = { path = "../crates/ytm-config" }

[[bin]]
name = "parse_response"
path = "fuzz_targets/parse_response.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_lrc"
path = "fuzz_targets/parse_lrc.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_binding"
path = "fuzz_targets/parse_binding.rs"
test = false
doc = false
bench = false
