[package]
name = "ytm-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ytm-core = { path = "../ytm-core" }
ytm-api = { path = "../ytm-api" }
ytm-player = { path = "../ytm-player" }
ytm-viz = { path = "../ytm-viz" }
anyhow.workspace = true
ratatui.workspace = true
arc-swap.workspace = true
unicode-width = "0.2"
